const $=id=>document.getElementById(id);
const state={map:null,sourceMarkers:[],route:null,destination:null};
const cctvEvents=[{lat:13.0827,lng:80.2707,count:18,label:'Central monitoring zone'},{lat:13.0674,lng:80.2376,count:11,label:'West CCTV cluster'},{lat:13.0358,lng:80.2453,count:7,label:'South monitoring zone'},{lat:13.1001,lng:80.2894,count:14,label:'North CCTV cluster'},{lat:13.0475,lng:80.2598,count:5,label:'East monitoring zone'}];
function initMap(){state.map=L.map('map',{zoomControl:true,preferCanvas:true}).setView([13.0827,80.2707],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(state.map);renderHeatmap();setTimeout(()=>state.map.invalidateSize(),150)}
function renderHeatmap(){state.sourceMarkers.forEach(m=>state.map.removeLayer(m));state.sourceMarkers=[];cctvEvents.forEach(e=>{const radius=260+e.count*18,opacity=Math.min(.46,.13+e.count*.012);const outer=L.circle([e.lat,e.lng],{radius,color:'#ff665f',weight:1,fillColor:'#ff665f',fillOpacity:opacity}).addTo(state.map);outer.bindPopup(`<b>${e.label}</b><br>${e.count} CCTV dog detections in this area<br><small>Heat intensity represents detection density.</small>`);const inner=L.circle([e.lat,e.lng],{radius:Math.max(70,radius*.32),color:'#ffb36b',weight:0,fillColor:'#ffb36b',fillOpacity:Math.min(.32,opacity+.08),interactive:false}).addTo(state.map);state.sourceMarkers.push(outer,inner)});$('zoneCount').textContent=cctvEvents.length;const dc=$('detectionCount');if(dc)dc.textContent=cctvEvents.reduce((a,e)=>a+e.count,0)}
function addCctvDetection(){const base=cctvEvents[cctvEvents.length%5];const e={lat:base.lat+0.003*(Math.random()-.5),lng:base.lng+0.003*(Math.random()-.5),count:1+Math.floor(Math.random()*8),label:'New CCTV detection cluster'};cctvEvents.push(e);renderHeatmap();state.map.setView([e.lat,e.lng],13);$('alertToast').classList.add('show');setTimeout(()=>$('alertToast').classList.remove('show'),4500)}
function fileReady(f){if(!f||!f.type.startsWith('image/'))return;const r=new FileReader();r.onload=e=>{$('preview').src=e.target.result;$('previewWrap').classList.remove('hidden');$('dropZone').classList.add('hidden');$('detectionResult').innerHTML='<div class="result-empty"><span>◌</span><p>CCTV frame ready<br><small>Run detection to simulate adding this frame to the monitoring pipeline.</small></p></div>'};r.readAsDataURL(f)}
function detect(){if($('previewWrap').classList.contains('hidden'))return $('imageInput').click();$('detectBtn').disabled=true;$('detectBtn').innerHTML='Analyzing frame <span>…</span>';$('detectionResult').innerHTML='<div class="result-empty"><span>◌</span><p>Running CCTV frame analysis<br><small>Demo inference flow — production will consume the CCTV backend.</small></p></div>';setTimeout(()=>{const c=(91+Math.random()*7).toFixed(1);$('detectionResult').innerHTML=`<div class="result-card"><div><small>DETECTION SOURCE</small><strong>CCTV frame</strong></div><div class="zone">Heatmap update</div><div class="confidence"><i style="width:${c}%"></i></div><small>MODEL CONFIDENCE</small><small>${c}%</small></div>`;addCctvDetection();$('detectBtn').disabled=false;$('detectBtn').innerHTML='Process CCTV frame <span>→</span>'},1100)}
function route(){const name=$('destination').value.trim();if(!name)return $('destination').focus();if(state.route)state.map.removeLayer(state.route);const s=L.latLng(13.0827,80.2707),hot=cctvEvents.reduce((a,b)=>a.count>b.count?a:b),t=L.latLng(hot.lat,hot.lng),path=[[s.lat,s.lng],[s.lat+.006,s.lng-.006],[t.lat+.006,t.lng-.006],[t.lat+.009,t.lng+.009]];state.route=L.polyline(path,{color:'#65f2ae',weight:5,opacity:.9,dashArray:'9 8'}).addTo(state.map);if(state.destination)state.map.removeLayer(state.destination);state.destination=L.marker(path.at(-1)).addTo(state.map).bindPopup('<b>Safer route</b><br>'+name);state.map.fitBounds(state.route.getBounds(),{padding:[60,60]});$('detectionResult').insertAdjacentHTML('beforeend','<p class="route-note">✓ Route visualized to avoid the highest-density CCTV dog hotspot.</p>')}
function reveal(){const els=document.querySelectorAll('.reveal');if(!('IntersectionObserver'in window))return els.forEach(e=>e.classList.add('visible'));const o=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');o.unobserve(e.target)}}),{threshold:.12});els.forEach(e=>o.observe(e))}
document.addEventListener('DOMContentLoaded',()=>{initMap();reveal();const i=$('imageInput'),d=$('dropZone');i.addEventListener('change',e=>fileReady(e.target.files[0]));d.addEventListener('dragover',e=>{e.preventDefault();d.classList.add('dragging')});d.addEventListener('dragleave',()=>d.classList.remove('dragging'));d.addEventListener('drop',e=>{e.preventDefault();d.classList.remove('dragging');fileReady(e.dataTransfer.files[0])});$('detectBtn').addEventListener('click',detect);$('removeImage').addEventListener('click',()=>{$('preview').src='';$('previewWrap').classList.add('hidden');$('dropZone').classList.remove('hidden');i.value=''});$('routeBtn').addEventListener('click',route);$('closeToast').addEventListener('click',()=>$('alertToast').classList.remove('show'))});